export type CloudinaryResource = {
  asset_id: string;
  public_id: string;
  secure_url: string;
  width?: number;
  height?: number;
};

export type PortfolioAsset = {
  id: string;
  title: string;
  label: string;
  note: string;
  alt: string;
  imageUrl: string;
  width: number;
  height: number;
  sessionId?: string;
  sessionName?: string;
  sessionDate?: string;
  isSessionCover?: boolean;
  excludeFromCarousel?: boolean;
  isVideo?: boolean;
  isHeroOnly?: boolean;
  coverObjectPosition?: string;
  coverTransform?: string;
  startsNewRow?: boolean;
};

export type PortfolioModule = {
  slug: string;
  menuLabel: string;
  title: string;
  subtitle: string;
  tags: string[];
  galleryHeading: string;
  sequenceHeading: string;
};

export const portfolioModules: PortfolioModule[] = [
  {
    slug: "key-projects",
    menuLabel: "Key Projects",
    title: "Key Projects",
    subtitle: "A curated selection of projects that reflect my creative vision, versatility, and attention to detail. This collection features campaigns, music videos, and other significant creative productions I’ve had the opportunity to be part of. Each project represents a distinct artistic experience, crafted with intention and elevated through beauty, storytelling, and visual direction.",
    tags: ["Beauty", "Campaign", "Portfolio", "Signature"],
    galleryHeading: "Featured projects",
    sequenceHeading: "Project sequence",
  },
  {
    slug: "photoshoot",
    menuLabel: "Photoshoot",
    title: "Photoshoot",
    subtitle: "An image-led module focused on polished beauty direction, clean skin work and editorial precision in front of the camera.",
    tags: ["Beauty", "Editorial", "Skin", "Photoshoot"],
    galleryHeading: "Selected work",
    sequenceHeading: "More looks",
  },
  {
    slug: "editorials",
    menuLabel: "Editorials",
    title: "Editorials",
    subtitle: "Editorial beauty looks with a sharper rhythm, balancing concept, light and finish for magazine-style imagery.",
    tags: ["Editorial", "Beauty", "Fashion", "Studio"],
    galleryHeading: "Editorial spread",
    sequenceHeading: "Editorial sequence",
  },
  {
    slug: "social-glam",
    menuLabel: "Social Glam",
    title: "Social Glam",
    subtitle: "High-finish glam looks built for camera-ready events, night lighting and polished social content.",
    tags: ["Glam", "Events", "Camera", "Glow"],
    galleryHeading: "Glam selection",
    sequenceHeading: "Glam sequence",
  },
  {
    slug: "timeless-beauty",
    menuLabel: "Timeless Beauty",
    title: "Timeless Beauty",
    subtitle: "Classic makeup direction with modern restraint, centered on skin, structure and a lasting elegant finish.",
    tags: ["Classic", "Skin", "Elegant", "Timeless"],
    galleryHeading: "Timeless looks",
    sequenceHeading: "Beauty sequence",
  },
  {
    slug: "hair",
    menuLabel: "Hair",
    title: "Hair",
    subtitle: "",
    tags: ["Hair", "Styling", "Texture", "Editorial"],
    galleryHeading: "Hair sessions",
    sequenceHeading: "Hair sequence",
  },
];

export const curatedAssets: PortfolioAsset[] = [
  {
    id: "Mira-7423",
    title: "Beauty Look 01",
    label: "Hero",
    note: "Luminous skin and clean editorial finish.",
    alt: "Makeup portfolio portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778703619/Mira-7423_leg8rt.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Mira-7362",
    title: "Beauty Look 02",
    label: "Skin focus",
    note: "Refined complexion work for camera-ready beauty.",
    alt: "Professional makeup detail",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778703618/Mira-7362_lpntg4.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Mira-6301",
    title: "Beauty Look 03",
    label: "Beauty detail",
    note: "Portrait beauty work with clean definition.",
    alt: "Beauty portrait with makeup focus",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778703612/Mira-6301_ifo2hi.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Mira-6313",
    title: "Beauty Look 04",
    label: "Soft glam",
    note: "Balanced eyes, lips and skin finish.",
    alt: "Soft glam makeup portfolio look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778703611/Mira-6313_o07swg.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Mo5294",
    title: "Beauty Look 05",
    label: "Editorial clean",
    note: "Clean editorial makeup direction.",
    alt: "Clean editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778703366/Mo5294_dt1liu.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Mo3808",
    title: "Beauty Look 06",
    label: "Studio",
    note: "Elegant studio-ready makeup finish.",
    alt: "Studio makeup portfolio look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778703364/Mo3808_gnwpo9.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Mo2107",
    title: "Beauty Look 07",
    label: "Polished",
    note: "Defined features with polished beauty direction.",
    alt: "Polished professional makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778703356/Mo2107_m8ql8f.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Rolando-Acunam-Kim019",
    title: "Beauty Look 08",
    label: "Campaign",
    note: "Campaign-ready beauty with crisp finish.",
    alt: "Beauty campaign makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778703047/Rolando.Acunam_Kim019_gyanlg.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Rolando-Acunam-Kim008",
    title: "Beauty Look 09",
    label: "Portrait",
    note: "Portrait makeup with clear skin focus.",
    alt: "Editorial makeup portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778703045/Rolando.Acunam_Kim008_hodkvp.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Rolando-Acunam-RWarehouse042",
    title: "Beauty Look 10",
    label: "Fashion",
    note: "Editorial fashion beauty direction.",
    alt: "Fashion beauty makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778702933/Rolando.Acunam_RWarehouse042_xmyuec.jpg",
    width: 1400,
    height: 1750,
  },
  {
    id: "Rolando-Acunam-RWarehouse031",
    title: "Beauty Look 11",
    label: "Final",
    note: "Strong closing image with consistent finish.",
    alt: "Closing image for makeup portfolio",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/q_auto/f_auto/v1778700638/Rolando.Acunam_RWarehouse031_uj3c57.jpg",
    width: 1400,
    height: 1750,
  },
];

export const editorialAssets: PortfolioAsset[] = [
  // Primary Editorial Hero Cover (3rd photo of Series II - Part 1)
  {
    id: "edit-series-2-3",
    title: "Editorial Look 05",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771435/Photo_Jul_20_2026_8_44_24_PM_4_ncpxxc.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-ii-a",
    sessionName: "Editorial Series II - Part 1",
    sessionDate: "Collection II-A",
  },
  {
    id: "edit-series-2-1",
    title: "Editorial Look 01",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771440/Photo_Jul_20_2026_8_44_24_PM_5_1_ijga90.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-ii-a",
    sessionName: "Editorial Series II - Part 1",
    sessionDate: "Collection II-A",
    isSessionCover: true,
  },
  {
    id: "edit-series-1-1",
    title: "Editorial Look 02",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771470/Photo_Jun_06_2026_4_24_11_AM_wgntwu.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-i",
    sessionName: "Editorial Series I",
    sessionDate: "Collection I",
    isSessionCover: true,
  },
  {
    id: "edit-series-1-2",
    title: "Editorial Look 02-B",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771469/Photo_Jun_06_2026_4_46_16_AM_erkat3.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-i",
    sessionName: "Editorial Series I",
    sessionDate: "Collection I",
  },
  {
    id: "edit-series-1-3",
    title: "Editorial Look 03",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771468/Photo_Jun_06_2026_4_24_11_AM_1_wgntwu.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-i",
    sessionName: "Editorial Series I",
    sessionDate: "Collection I",
  },
  {
    id: "edit-series-2-2",
    title: "Editorial Look 04",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771439/Photo_Jul_20_2026_8_44_24_PM_5_ezb9fj.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-ii-a",
    sessionName: "Editorial Series II - Part 1",
    sessionDate: "Collection II-A",
  },

  // Series II - Part 2 (Fotos 4, 5, 6, 7)
  {
    id: "edit-series-2-4",
    title: "Editorial Look 06",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771435/Photo_Jul_20_2026_8_44_24_PM_3_uqd5km.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-ii-b",
    sessionName: "Editorial Series II - Part 2",
    sessionDate: "Collection II-B",
    isSessionCover: true,
  },
  {
    id: "edit-series-2-5",
    title: "Editorial Look 07",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771435/Photo_Jul_20_2026_8_44_24_PM_2_1_xnnb4a.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-ii-b",
    sessionName: "Editorial Series II - Part 2",
    sessionDate: "Collection II-B",
    excludeFromCarousel: true,
  },
  {
    id: "edit-series-2-6",
    title: "Editorial Look 08",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771433/Photo_Jul_20_2026_8_44_24_PM_sbnidh.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-ii-b",
    sessionName: "Editorial Series II - Part 2",
    sessionDate: "Collection II-B",
  },
  {
    id: "edit-series-2-7",
    title: "Editorial Look 09",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771433/Photo_Jul_20_2026_8_44_24_PM_1_zqnzy1.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-ii-b",
    sessionName: "Editorial Series II - Part 2",
    sessionDate: "Collection II-B",
  },

  // Series III - Part 1
  {
    id: "edit-series-3-cover",
    title: "Editorial Look 10",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788718680/Photo_Jul_20_2026_8_47_47_PM_5_tyzorf.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-a",
    sessionName: "Editorial Series III - Part 1",
    sessionDate: "Collection III-A",
    isSessionCover: true,
  },
  {
    id: "edit-series-3-1",
    title: "Editorial Look 10-B",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771463/Photo_Jul_20_2026_8_47_47_PM_13_dazsxo.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-a",
    sessionName: "Editorial Series III - Part 1",
    sessionDate: "Collection III-A",
  },
  {
    id: "edit-series-3-2",
    title: "Editorial Look 11",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771462/Photo_Jul_20_2026_8_47_47_PM_12_wgbzwz.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-a",
    sessionName: "Editorial Series III - Part 1",
    sessionDate: "Collection III-A",
  },
  {
    id: "edit-series-3-3",
    title: "Editorial Look 12",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771461/Photo_Jul_20_2026_8_47_47_PM_11_amb2hd.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-a",
    sessionName: "Editorial Series III - Part 1",
    sessionDate: "Collection III-A",
  },
  {
    id: "edit-series-3-5",
    title: "Editorial Look 14",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771459/Photo_Jul_20_2026_8_47_47_PM_9_up937r.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-a",
    sessionName: "Editorial Series III - Part 1",
    sessionDate: "Collection III-A",
  },
  {
    id: "edit-series-3-7",
    title: "Editorial Look 16",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771455/Photo_Jul_20_2026_8_47_47_PM_7_xnkzj8.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-a",
    sessionName: "Editorial Series III - Part 1",
    sessionDate: "Collection III-A",
  },
  {
    id: "edit-series-3-8",
    title: "Editorial Look 17",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771453/Photo_Jul_20_2026_8_47_47_PM_6_zvjb7v.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-a",
    sessionName: "Editorial Series III - Part 1",
    sessionDate: "Collection III-A",
  },

  // Series III - Part 2 (Fotos 4, 6)
  {
    id: "edit-series-3-4",
    title: "Editorial Look 13",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771460/Photo_Jul_20_2026_8_47_47_PM_10_vwotz4.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-b",
    sessionName: "Editorial Series III - Part 2",
    sessionDate: "Collection III-B",
    isSessionCover: true,
  },
  {
    id: "edit-series-3-6",
    title: "Editorial Look 15",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771456/Photo_Jul_20_2026_8_47_47_PM_8_mzjwlt.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-b",
    sessionName: "Editorial Series III - Part 2",
    sessionDate: "Collection III-B",
    excludeFromCarousel: true,
  },

  // Series III - Part 3 (Fotos 9, 10, 11)
  {
    id: "edit-series-3-9",
    title: "Editorial Look 18",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771450/Photo_Jul_20_2026_8_47_47_PM_4_l5nwzv.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-c",
    sessionName: "Editorial Series III - Part 3",
    sessionDate: "Collection III-C",
    isSessionCover: true,
  },
  {
    id: "edit-series-3-10",
    title: "Editorial Look 19",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771449/Photo_Jul_20_2026_8_47_47_PM_3_ixweno.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-c",
    sessionName: "Editorial Series III - Part 3",
    sessionDate: "Collection III-C",
  },
  {
    id: "edit-series-3-11",
    title: "Editorial Look 20",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771448/Photo_Jul_20_2026_8_47_47_PM_2_yjld2k.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-c",
    sessionName: "Editorial Series III - Part 3",
    sessionDate: "Collection III-C",
  },

  // Series III - Part 4 (Fotos 12, 14)
  {
    id: "edit-series-3-12",
    title: "Editorial Look 21",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771445/Photo_Jul_20_2026_8_47_47_PM_1_1_bcmpko.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-d",
    sessionName: "Editorial Series III - Part 4",
    sessionDate: "Collection III-D",
    isSessionCover: true,
  },
  {
    id: "edit-series-3-14",
    title: "Editorial Look 23",
    label: "Editorial",
    note: "Clean editorial beauty direction.",
    alt: "Editorial makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1784771441/Photo_Jul_20_2026_8_47_47_PM_gh1x8o.jpg",
    width: 1400,
    height: 1750,
    sessionId: "series-iii-d",
    sessionName: "Editorial Series III - Part 4",
    sessionDate: "Collection III-D",
  },
];

export const keyProjectsAssets: PortfolioAsset[] = [
  // Session 3: Key Projects Series III (First element is used as Main Hero Cover)
  {
    id: "kp-hero-main",
    title: "Key Project Main Cover",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785264497/Photo_Mar_10_2025_6_01_28_PM_gwd8ks.jpg",
    width: 3024,
    height: 4032,
    isHeroOnly: true,
  },
  {
    id: "kp-3-photo1",
    title: "Key Project Look 01",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177739/Photo_Jul_27_2026_11_23_40_AM_wjw9ep.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-3",
    sessionName: "Women of The Year 2025",
    sessionDate: "Collection III",
  },
  {
    id: "kp-3-photo2",
    title: "Key Project Look 02",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177741/Photo_Jul_27_2026_11_23_40_AM_1_udizyz.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-3",
    sessionName: "Women of The Year 2025",
    sessionDate: "Collection III",
    isSessionCover: true,
  },
  {
    id: "kp-3-photo3",
    title: "Key Project Look 03",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177743/Photo_Jul_27_2026_11_23_40_AM_2_xtq8zr.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-3",
    sessionName: "Women of The Year 2025",
    sessionDate: "Collection III",
  },
  {
    id: "kp-3-intercalated-1",
    title: "Key Project Look 03-B",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177742/Photo_Nov_05_2025_5_46_42_PM_wymm7z.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-3",
    sessionName: "Women of The Year 2025",
    sessionDate: "Collection III",
  },
  {
    id: "kp-3-photo4",
    title: "Key Project Look 04",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177744/Photo_Jul_27_2026_11_23_40_AM_3_bl1bsu.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-3",
    sessionName: "Women of The Year 2025",
    sessionDate: "Collection III",
  },
  {
    id: "kp-3-photo5",
    title: "Key Project Look 05",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177747/Photo_Jul_27_2026_11_23_41_AM_r4rhoq.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-3",
    sessionName: "Women of The Year 2025",
    sessionDate: "Collection III",
  },
  {
    id: "kp-3-intercalated-2",
    title: "Key Project Look 05-B",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177742/Photo_Nov_05_2025_5_46_46_PM_hplais.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-3",
    sessionName: "Women of The Year 2025",
    sessionDate: "Collection III",
  },

  // Session 2: Key Projects Series II
  {
    id: "kp-2-photo1",
    title: "Key Project Look 06",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177721/Photo_Jul_27_2026_11_09_35_AM_3_sns3yp.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-2",
    sessionName: "BAD BUNNY  - EL CLúB",
    sessionDate: "Collection II",
    isSessionCover: true,
  },
  {
    id: "kp-2-photo2",
    title: "Key Project Look 07",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177720/Photo_Jul_27_2026_11_09_35_AM_2_1_ydbjmn.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-2",
    sessionName: "BAD BUNNY  - EL CLúB",
    sessionDate: "Collection II",
  },
  {
    id: "kp-2-photo3",
    title: "Key Project Look 08",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177723/Photo_Jul_27_2026_11_09_35_AM_4_vuopoh.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-2",
    sessionName: "BAD BUNNY  - EL CLúB",
    sessionDate: "Collection II",
  },
  {
    id: "kp-2-photo4",
    title: "Key Project Look 09",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177727/Photo_Jul_27_2026_11_09_35_AM_6_obauqg.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-2",
    sessionName: "BAD BUNNY  - EL CLúB",
    sessionDate: "Collection II",
    excludeFromCarousel: true,
  },
  {
    id: "kp-2-photo5",
    title: "Key Project Look 10",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177730/Photo_Jul_27_2026_11_09_35_AM_9_oouhvr.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-2",
    sessionName: "BAD BUNNY  - EL CLúB",
    sessionDate: "Collection II",
    excludeFromCarousel: true,
  },
  {
    id: "kp-2-photo6",
    title: "Key Project Look 11",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177731/Photo_Jul_27_2026_11_09_35_AM_11_fqs6s4.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-2",
    sessionName: "BAD BUNNY  - EL CLúB",
    sessionDate: "Collection II",
  },
  {
    id: "kp-2-photo7",
    title: "Key Project Look 12",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177735/Photo_Jul_27_2026_11_09_35_AM_14_hnl0g9.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-2",
    sessionName: "BAD BUNNY  - EL CLúB",
    sessionDate: "Collection II",
    excludeFromCarousel: true,
  },
  {
    id: "kp-2-photo8",
    title: "Key Project Look 13",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177734/Photo_Jul_27_2026_11_09_35_AM_13_mqzyf4.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-2",
    sessionName: "BAD BUNNY  - EL CLúB",
    sessionDate: "Collection II",
    excludeFromCarousel: true,
  },
  {
    id: "kp-2-photo9",
    title: "Key Project Look 14",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177736/Photo_Jul_27_2026_11_09_35_AM_14_1_vpdhzo.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-2",
    sessionName: "BAD BUNNY  - EL CLúB",
    sessionDate: "Collection II",
    excludeFromCarousel: true,
  },

  // Session 1: Key Projects Series I
  {
    id: "kp-1-photo1",
    title: "Key Project Look 15",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177773/Photo_Feb_12_2026_3_09_10_PM_yoykax.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
  },
  {
    id: "kp-1-photo2",
    title: "Key Project Look 16",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177772/Photo_Feb_12_2026_1_41_05_PM_pxzyrh.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
    isSessionCover: true,
    excludeFromCarousel: true,
  },
  {
    id: "kp-1-photo3",
    title: "Key Project Look 17",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177769/Photo_Feb_14_2026_10_04_59_PM_zilzxn.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
  },
  {
    id: "kp-1-photo4",
    title: "Key Project Look 18",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177766/Photo_Feb_12_2026_12_03_44_PM_updtqa.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
  },
  {
    id: "kp-1-video",
    title: "Key Project Look 15 - Video",
    label: "Key Projects",
    note: "Video capture of key project look.",
    alt: "Key project beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785177763/Video_Feb_12_2026_11_58_57_AM_ipnv2d.mp4",
    width: 1080,
    height: 1920,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
    isVideo: true,
  },
  {
    id: "kp-1-added-6",
    title: "Key Project Look 18-B",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786309993/IMG_4859_dl4p6a.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
  },
  {
    id: "kp-1-added-7",
    title: "Key Project Look 18-C",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786309991/IMG_4673_ptcstr.heic",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
  },
  {
    id: "kp-1-added-8",
    title: "Key Project Look 18-D",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786309992/IMG_4860_ys1qpj.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
  },
  {
    id: "kp-1-added-9",
    title: "Key Project Look 18-E",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786309990/IMG_4662_r8jxyd.heic",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
  },
  {
    id: "kp-1-added-10",
    title: "Key Project Look 18-F",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177778/Photo_Feb_14_2026_10_04_42_PM_ntwe4o.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
  },
  {
    id: "kp-1-added-11",
    title: "Key Project Look 18-G",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786309990/IMG_4657_ckwsfl.heic",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-1",
    sessionName: "NYFW’26 - Yinam",
    sessionDate: "Collection I",
  },

  // Session 4: Key Projects Series IV
  {
    id: "kp-4-photo1",
    title: "Key Project Look 19",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177753/Photo_Apr_21_2026_10_15_48_AM_hgtygc.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-4",
    sessionName: "Izzy Escobar - The Devil Wears Prada 2 premiere",
    sessionDate: "Collection IV",
  },
  {
    id: "kp-4-video",
    title: "Key Project Look 19 - Video",
    label: "Key Projects",
    note: "Video capture of key project look.",
    alt: "Key project beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785177754/Video_Apr_21_2026_10_18_13_AM_gxljp6.mp4",
    width: 1080,
    height: 1920,
    sessionId: "kp-series-4",
    sessionName: "Izzy Escobar - The Devil Wears Prada 2 premiere",
    sessionDate: "Collection IV",
    isVideo: true,
  },
  {
    id: "kp-4-photo2",
    title: "Key Project Look 20",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177756/Photo_Apr_24_2026_3_27_43_PM_dluex5.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-4",
    sessionName: "Izzy Escobar - The Devil Wears Prada 2 premiere",
    sessionDate: "Collection IV",
  },
  {
    id: "kp-4-photo3",
    title: "Key Project Look 21",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177757/Photo_Apr_24_2026_3_32_38_PM_mjcmlc.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-4",
    sessionName: "Izzy Escobar - The Devil Wears Prada 2 premiere",
    sessionDate: "Collection IV",
  },

  // Session 5: Key Projects Series V
  {
    id: "kp-5-photo1",
    title: "Key Project Look 22",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177717/Photo_Jul_24_2026_11_15_32_AM_1_pjbeia.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-5",
    sessionName: "Vitafer - Tito Double P ft Dareyes de la Sierra",
    sessionDate: "Collection V",
  },
  {
    id: "kp-5-video",
    title: "Key Project Look 22 - Video",
    label: "Key Projects",
    note: "Video capture of key project look.",
    alt: "Key project beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785177717/Video_Mar_10_2025_10_09_51_PM_fhkdgb.mp4",
    width: 1080,
    height: 1920,
    sessionId: "kp-series-5",
    sessionName: "Vitafer - Tito Double P ft Dareyes de la Sierra",
    sessionDate: "Collection V",
    isVideo: true,
  },
  {
    id: "kp-5-photo2",
    title: "Key Project Look 23",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177715/Photo_Jul_24_2026_11_15_32_AM_o191f7.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-5",
    sessionName: "Vitafer - Tito Double P ft Dareyes de la Sierra",
    sessionDate: "Collection V",
    excludeFromCarousel: true,
  },
  {
    id: "kp-5-photo3",
    title: "Key Project Look 24",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177714/Photo_Mar_10_2025_10_31_35_PM_gk8a58.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-5",
    sessionName: "Vitafer - Tito Double P ft Dareyes de la Sierra",
    sessionDate: "Collection V",
    isSessionCover: true,
  },
  {
    id: "kp-5-photo4",
    title: "Key Project Look 25",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177713/Photo_Mar_10_2025_10_10_28_PM_tetbum.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-5",
    sessionName: "Vitafer - Tito Double P ft Dareyes de la Sierra",
    sessionDate: "Collection V",
  },

  // Session 8: Key Projects Series VIII
  {
    id: "kp-8-photo2",
    title: "Key Project Look 29",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177765/Photo_Feb_09_2026_12_59_20_PM_pzihfk.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-8",
    sessionName: "NYFW’26 - Roots",
    sessionDate: "Collection VIII",
    isSessionCover: true,
  },
  {
    id: "kp-8-added-4",
    title: "Key Project Look 32-E",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788373064/IMG_4613_d3lr30.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-8",
    sessionName: "NYFW’26 - Roots",
    sessionDate: "Collection VIII",
  },
  {
    id: "kp-8-added-5",
    title: "Key Project Look 32-F",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788373058/IMG_4619_ojwntl.webp",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-8",
    sessionName: "NYFW’26 - Roots",
    sessionDate: "Collection VIII",
  },
  {
    id: "kp-8-added-3",
    title: "Key Project Look 32-D",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788370973/Photo_Jul_27_2026_11_31_46_AM_yijqyj.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-8",
    sessionName: "NYFW’26 - Roots",
    sessionDate: "Collection VIII",
  },
  {
    id: "kp-8-added-2",
    title: "Key Project Look 32-C",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/c_crop,g_north,h_0.85/v1788370973/Photo_Feb_09_2026_3_54_18_PM_buzagb.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-8",
    sessionName: "NYFW’26 - Roots",
    sessionDate: "Collection VIII",
  },
  {
    id: "kp-8-photo3",
    title: "Key Project Look 30",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786309999/IMG_4578_tc2yji.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-8",
    sessionName: "NYFW’26 - Roots",
    sessionDate: "Collection VIII",
  },
  {
    id: "kp-8-added-1",
    title: "Key Project Look 32-B",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788370973/Photo_Feb_10_2026_3_16_31_PM_kf2pxx.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-8",
    sessionName: "NYFW’26 - Roots",
    sessionDate: "Collection VIII",
  },
  {
    id: "kp-8-photo1",
    title: "Key Project Look 28",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785177765/Photo_Feb_09_2026_12_59_50_PM_ghvbiq.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-8",
    sessionName: "NYFW’26 - Roots",
    sessionDate: "Collection VIII",
  },
  {
    id: "kp-8-photo4",
    title: "Key Project Look 31",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786309998/IMG_4579_qerdpa.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-8",
    sessionName: "NYFW’26 - Roots",
    sessionDate: "Collection VIII",
  },

  // Session 9: Key Projects Series IX
  {
    id: "kp-9-photo1",
    title: "Key Project Look 33",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786310039/IMG_6740_mkz6uk.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-9",
    sessionName: "Campaign - Kajal New York",
    sessionDate: "Collection IX",
    isSessionCover: true,
  },
  {
    id: "kp-9-photo2",
    title: "Key Project Look 34",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786310039/IMG_6739_srzlsk.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-9",
    sessionName: "Campaign - Kajal New York",
    sessionDate: "Collection IX",
  },
  {
    id: "kp-9-photo4",
    title: "Key Project Look 36",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786310036/IMG_6640_lxssaw.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-9",
    sessionName: "Campaign - Kajal New York",
    sessionDate: "Collection IX",
  },
  {
    id: "kp-9-photo5",
    title: "Key Project Look 37",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786310035/IMG_6639_ira3ep.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-9",
    sessionName: "Campaign - Kajal New York",
    sessionDate: "Collection IX",
  },
  {
    id: "kp-9-photo6",
    title: "Key Project Look 38",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786310029/IMG_6638_oucvfc.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-9",
    sessionName: "Campaign - Kajal New York",
    sessionDate: "Collection IX",
  },
  {
    id: "kp-9-photo8",
    title: "Key Project Look 40",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786310003/IMG_6630_kolcfb.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-9",
    sessionName: "Campaign - Kajal New York",
    sessionDate: "Collection IX",
  },
  {
    id: "kp-9-photo9",
    title: "Key Project Look 41",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786310004/IMG_6631_i0yvyg.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-9",
    sessionName: "Campaign - Kajal New York",
    sessionDate: "Collection IX",
  },

  // Session 10: Key Projects Series X
  {
    id: "kp-10-cover",
    title: "Key Project Look 42",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788362063/Photo_Aug_28_2026_5_30_38_PM_am8tb3.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-10",
    sessionName: "4 videoclips - Izzy Escobar",
    sessionDate: "Collection X",
    isSessionCover: true,
  },
  {
    id: "kp-10-photo1",
    title: "Key Project Look 43",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788361381/WhatsApp_Image_2026-08-28_at_5.34.23_PM_q4gqvg.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-10",
    sessionName: "4 videoclips - Izzy Escobar",
    sessionDate: "Collection X",
  },
  {
    id: "kp-10-photo2",
    title: "Key Project Look 44",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788361380/WhatsApp_Image_2026-08-28_at_5.34.21_PM_1_tmwaql.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-10",
    sessionName: "4 videoclips - Izzy Escobar",
    sessionDate: "Collection X",
  },
  {
    id: "kp-10-photo3",
    title: "Key Project Look 45",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788361381/WhatsApp_Image_2026-08-28_at_5.34.22_PM_qnqiau.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-10",
    sessionName: "4 videoclips - Izzy Escobar",
    sessionDate: "Collection X",
  },
  {
    id: "kp-10-photo4",
    title: "Key Project Look 46",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788361380/WhatsApp_Image_2026-08-28_at_5.34.21_PM_nrkpe8.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-10",
    sessionName: "4 videoclips - Izzy Escobar",
    sessionDate: "Collection X",
  },
  {
    id: "kp-10-video",
    title: "Key Project Look 47 - Video",
    label: "Key Projects",
    note: "Video capture of key project look.",
    alt: "Key project beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1788362062/Video_Oct_03_2025_5_32_51_PM_sc92fz.mp4",
    width: 1080,
    height: 1920,
    sessionId: "kp-series-10",
    sessionName: "4 videoclips - Izzy Escobar",
    sessionDate: "Collection X",
    isVideo: true,
  },
  {
    id: "kp-10-photo5",
    title: "Key Project Look 48",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788362062/Photo_Oct_03_2025_11_57_46_AM_jzhori.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-10",
    sessionName: "4 videoclips - Izzy Escobar",
    sessionDate: "Collection X",
  },
  {
    id: "kp-10-photo6",
    title: "Key Project Look 49",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788362062/Photo_Jul_27_2026_11_09_35_AM_2_cswie0.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-10",
    sessionName: "4 videoclips - Izzy Escobar",
    sessionDate: "Collection X",
  },
  // Session 11: Campaign - Reveform
  {
    id: "kp-11-photo1",
    title: "Key Project Look 50",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788639058/IMG_5783_rdfrce.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-11",
    sessionName: "Campaign - Reveform",
    sessionDate: "Collection XI",
    isSessionCover: true,
  },
  {
    id: "kp-11-photo2",
    title: "Key Project Look 51",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788639058/IMG_7942_ydjrpm.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-11",
    sessionName: "Campaign - Reveform",
    sessionDate: "Collection XI",
  },
  {
    id: "kp-11-photo3",
    title: "Key Project Look 52",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788639059/IMG_7943_st66kf.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-11",
    sessionName: "Campaign - Reveform",
    sessionDate: "Collection XI",
  },
  {
    id: "kp-11-photo4",
    title: "Key Project Look 53",
    label: "Key Projects",
    note: "Standout beauty direction and campaign focus.",
    alt: "Key project beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788639058/IMG_5776_ldraej.jpg",
    width: 1400,
    height: 1750,
    sessionId: "kp-series-11",
    sessionName: "Campaign - Reveform",
    sessionDate: "Collection XI",
  },
  {
    id: "kp-11-video1",
    title: "Key Project Look 54 - Video",
    label: "Key Projects",
    note: "Video capture of key project look.",
    alt: "Key project beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1788639058/ScreenRecording_08-21-2026_11-43-47_1_oo04hc.mp4",
    width: 1080,
    height: 1920,
    sessionId: "kp-series-11",
    sessionName: "Campaign - Reveform",
    sessionDate: "Collection XI",
    isVideo: true,
  },
];

export const timelessAssets: PortfolioAsset[] = [
  // Session 1: Timeless Series I
  {
    id: "tb-1-photo",
    title: "Timeless Look 01",
    label: "Timeless",
    note: "Classic beauty direction with refined finish.",
    alt: "Timeless beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785101720/Photo_Apr_25_2026_1_44_28_PM_ngurum.jpg",
    width: 1400,
    height: 1750,
    sessionId: "tb-series-1",
    sessionName: "Timeless Series I",
    sessionDate: "Collection I",
    isSessionCover: true,
  },
  {
    id: "tb-1-video",
    title: "Timeless Look 01 - Video",
    label: "Timeless",
    note: "Video capture of timeless look.",
    alt: "Timeless beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785101721/Video_Apr_25_2026_1_44_19_PM_gdoga3.mp4",
    width: 1080,
    height: 1920,
    sessionId: "tb-series-1",
    sessionName: "Timeless Series I",
    sessionDate: "Collection I",
    isVideo: true,
  },

  // Session 2: Timeless Series II
  {
    id: "tb-2-photo1",
    title: "Timeless Look 02",
    label: "Timeless",
    note: "Classic beauty direction with refined finish.",
    alt: "Timeless beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785101717/Photo_Jun_28_2025_6_36_01_PM_wmho9u.jpg",
    width: 1400,
    height: 1750,
    sessionId: "tb-series-2",
    sessionName: "Timeless Series II",
    sessionDate: "Collection II",
  },
  {
    id: "tb-2-photo2",
    title: "Timeless Look 03",
    label: "Timeless",
    note: "Classic beauty direction with refined finish.",
    alt: "Timeless beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785101718/Photo_Jun_28_2025_6_38_43_PM_qh0roy.jpg",
    width: 1400,
    height: 1750,
    sessionId: "tb-series-2",
    sessionName: "Timeless Series II",
    sessionDate: "Collection II",
    isSessionCover: true,
  },
  {
    id: "tb-2-video",
    title: "Timeless Look 02 - Video",
    label: "Timeless",
    note: "Video capture of timeless look.",
    alt: "Timeless beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785101718/Video_Jul_24_2025_8_54_19_PM_uv7qjo.mp4",
    width: 1080,
    height: 1920,
    sessionId: "tb-series-2",
    sessionName: "Timeless Series II",
    sessionDate: "Collection II",
    isVideo: true,
  },

  // Session 3: Timeless Series III
  {
    id: "tb-3-photo",
    title: "Timeless Look 04",
    label: "Timeless",
    note: "Classic beauty direction with refined finish.",
    alt: "Timeless beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785101719/Photo_Jun_06_2026_11_26_54_AM_wbffg5.jpg",
    width: 1400,
    height: 1750,
    sessionId: "tb-series-3",
    sessionName: "Timeless Series III",
    sessionDate: "Collection III",
    isSessionCover: true,
  },
  {
    id: "tb-3-video",
    title: "Timeless Look 04 - Video",
    label: "Timeless",
    note: "Video capture of timeless look.",
    alt: "Timeless beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785101720/Video_Jun_13_2026_11_57_09_AM_rnovam.mp4",
    width: 1080,
    height: 1920,
    sessionId: "tb-series-3",
    sessionName: "Timeless Series III",
    sessionDate: "Collection III",
    isVideo: true,
  },

  // Session 4: Timeless Series IV
  {
    id: "tb-4-photo1",
    title: "Timeless Look 05",
    label: "Timeless",
    note: "Classic beauty direction with refined finish.",
    alt: "Timeless beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785101716/Photo_Jun_28_2025_5_13_03_PM_ytbuu4.jpg",
    width: 1400,
    height: 1750,
    sessionId: "tb-series-4",
    sessionName: "Timeless Series IV",
    sessionDate: "Collection IV",
    isSessionCover: true,
  },
  {
    id: "tb-4-photo2",
    title: "Timeless Look 06",
    label: "Timeless",
    note: "Classic beauty direction with refined finish.",
    alt: "Timeless beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785101717/Photo_Jun_28_2025_5_13_20_PM_t0oczn.jpg",
    width: 1400,
    height: 1750,
    sessionId: "tb-series-4",
    sessionName: "Timeless Series IV",
    sessionDate: "Collection IV",
  },
  {
    id: "tb-4-video",
    title: "Timeless Look 05 - Video",
    label: "Timeless",
    note: "Video capture of timeless look.",
    alt: "Timeless beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785101717/Video_Jul_03_2025_11_05_59_PM_fvxhfn.mp4",
    width: 1080,
    height: 1920,
    sessionId: "tb-series-4",
    sessionName: "Timeless Series IV",
    sessionDate: "Collection IV",
    isVideo: true,
  },
];

export const socialGlamAssets: PortfolioAsset[] = [
  // Main Hero Cover
  {
    id: "sg-hero-main",
    title: "Social Glam Main Cover",
    label: "Social Glam",
    note: "High-finish glam look for camera-ready events and polished social content.",
    alt: "Social Glam hero portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785507039/Photo_Jul_30_2026_6_04_51_PM_lvmcui.jpg",
    width: 1400,
    height: 1750,
    isHeroOnly: true,
  },

  // Session 1: Feb 28, 2025
  {
    id: "sg-1-photo1",
    title: "Social Glam Look 01",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785268735/Photo_Feb_28_2025_2_16_37_PM_vq6zty.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-1",
    sessionName: "Social Glam Series I",
    sessionDate: "Collection I",
    isSessionCover: true,
  },
  {
    id: "sg-1-photo2",
    title: "Social Glam Look 02",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785268736/Photo_Feb_28_2025_2_16_49_PM_xkna5i.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-1",
    sessionName: "Social Glam Series I",
    sessionDate: "Collection I",
  },

  // Session 2: Jun 18, 2025
  {
    id: "sg-2-photo1",
    title: "Social Glam Look 03",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785268735/Photo_Jun_18_2025_7_56_04_PM_zkvjlr.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-2",
    sessionName: "Social Glam Series II",
    sessionDate: "Collection II",
    isSessionCover: true,
    coverTransform: "f_auto,q_auto,c_crop,w_2066,h_2582,x_0,y_600/c_scale,w_650,h_812",
  },
  {
    id: "sg-2-video1",
    title: "Social Glam Look 03 - Video",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_2,f_mp4,q_auto/v1785268738/Video_Jun_18_2025_7_56_02_PM_pnhbor.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-2",
    sessionName: "Social Glam Series II",
    sessionDate: "Collection II",
    isVideo: true,
  },

  // Session 3: Aug 07, 2025
  {
    id: "sg-3-photo1",
    title: "Social Glam Look 04",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785268736/Photo_Aug_07_2025_1_40_13_PM_nhcazk.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-3",
    sessionName: "Social Glam Series III",
    sessionDate: "Collection III",
    isSessionCover: true,
  },
  {
    id: "sg-3-photo2",
    title: "Social Glam Look 05",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785268740/Photo_Aug_07_2025_1_45_56_PM_tc73xm.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-3",
    sessionName: "Social Glam Series III",
    sessionDate: "Collection III",
  },
  {
    id: "sg-3-video1",
    title: "Social Glam Look 04 - Video",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785268741/Video_Aug_07_2025_1_39_44_PM_s5xugo.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-3",
    sessionName: "Social Glam Series III",
    sessionDate: "Collection III",
    isVideo: true,
  },

  // Session 4: Jun 20-24, 2026
  {
    id: "sg-4-photo1",
    title: "Social Glam Look 06",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785270058/Photo_Jun_24_2026_12_20_39_PM_ojddlg.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-4",
    sessionName: "Social Glam Series IV",
    sessionDate: "Collection IV",
    isSessionCover: true,
  },
  {
    id: "sg-4-photo2",
    title: "Social Glam Look 07",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785269277/Photo_Jun_20_2026_11_35_54_AM_evmju5.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-4",
    sessionName: "Social Glam Series IV",
    sessionDate: "Collection IV",
  },
  {
    id: "sg-4-video1",
    title: "Social Glam Look 06 - Video",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785270059/Video_Jun_24_2026_12_20_36_PM_jfeskw.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-4",
    sessionName: "Social Glam Series IV",
    sessionDate: "Collection IV",
    isVideo: true,
  },

  // Session 5: Feb 27, 2026
  {
    id: "sg-5-photo1",
    title: "Social Glam Look 08",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785268742/Photo_Feb_27_2026_1_27_33_PM_j15op9.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-5",
    sessionName: "Social Glam Series V",
    sessionDate: "Collection V",
    isSessionCover: true,
  },
  {
    id: "sg-5-video1",
    title: "Social Glam Look 08 - Video",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785268745/Video_Feb_27_2026_1_09_01_PM_wk4av9.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-5",
    sessionName: "Social Glam Series V",
    sessionDate: "Collection V",
    isVideo: true,
  },

  // Session 6: May 07-08, 2026
  {
    id: "sg-6-photo1",
    title: "Social Glam Look 09",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785269264/Photo_May_07_2026_1_37_37_PM_tnixpj.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-6",
    sessionName: "Social Glam Series VI",
    sessionDate: "Collection VI",
    isSessionCover: true,
  },
  {
    id: "sg-6-photo2",
    title: "Social Glam Look 10",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785269266/Photo_May_07_2026_1_38_02_PM_d6fwdx.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-6",
    sessionName: "Social Glam Series VI",
    sessionDate: "Collection VI",
  },
  {
    id: "sg-6-video1",
    title: "Social Glam Look 09 - Video 1",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785269274/Video_May_07_2026_1_35_18_PM_q6ctnq.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-6",
    sessionName: "Social Glam Series VI",
    sessionDate: "Collection VI",
    isVideo: true,
  },
  {
    id: "sg-6-video2",
    title: "Social Glam Look 09 - Video 2",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785269291/Video_May_08_2026_3_19_37_PM_vusfib.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-6",
    sessionName: "Social Glam Series VI",
    sessionDate: "Collection VI",
    isVideo: true,
  },

  // Session 7: Jun 12, 2026
  {
    id: "sg-7-photo1",
    title: "Social Glam Look 11",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785269275/Photo_Jun_12_2026_2_06_29_PM_vrpaoc.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-7",
    sessionName: "Social Glam Series VII",
    sessionDate: "Collection VII",
    isSessionCover: true,
  },
  {
    id: "sg-7-photo2",
    title: "Social Glam Look 11-B",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785269263/Photo_Apr_16_2026_1_42_57_PM_icuubf.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-7",
    sessionName: "Social Glam Series VII",
    sessionDate: "Collection VII",
  },
  {
    id: "sg-7-video1",
    title: "Social Glam Look 11 - Video",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785269291/Video_May_08_2026_3_19_37_PM_vusfib.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-7",
    sessionName: "Social Glam Series VII",
    sessionDate: "Collection VII",
    isVideo: true,
  },

  // Session 8: Jun 06-11, 2026
  {
    id: "sg-8-photo1",
    title: "Social Glam Look 12",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785269270/Photo_Jun_06_2026_12_16_07_PM_uqc56t.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-8",
    sessionName: "Social Glam Series VIII",
    sessionDate: "Collection VIII",
    isSessionCover: true,
  },
  {
    id: "sg-8-photo2",
    title: "Social Glam Look 13",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785269271/Photo_Jun_06_2026_12_52_46_PM_qbxkil.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-8",
    sessionName: "Social Glam Series VIII",
    sessionDate: "Collection VIII",
  },
  {
    id: "sg-8-video1",
    title: "Social Glam Look 12 - Video 1",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785270059/Video_Jun_11_2026_6_01_23_PM_fgrcy1.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-8",
    sessionName: "Social Glam Series VIII",
    sessionDate: "Collection VIII",
    isVideo: true,
  },
  {
    id: "sg-8-video2",
    title: "Social Glam Look 12 - Video 2",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785270060/Video_Jun_06_2026_12_17_05_PM_uz1swe.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-8",
    sessionName: "Social Glam Series VIII",
    sessionDate: "Collection VIII",
    isVideo: true,
  },
  {
    id: "sg-8-video3",
    title: "Social Glam Look 12 - Video 3",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785270065/Video_Jun_06_2026_12_44_10_PM_qpvw9u.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-8",
    sessionName: "Social Glam Series VIII",
    sessionDate: "Collection VIII",
    isVideo: true,
  },

  // Session 9: Feb 14, 2026
  {
    id: "sg-9-photo1",
    title: "Social Glam Look 15",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785269263/Photo_Feb_14_2026_2_11_26_PM_r1uuld.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-9",
    sessionName: "Social Glam Series IX",
    sessionDate: "Collection IX",
    isSessionCover: true,
  },
  {
    id: "sg-9-photo2",
    title: "Social Glam Look 16",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785268799/Photo_Feb_14_2026_11_21_00_AM_arktqg.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-9",
    sessionName: "Social Glam Series IX",
    sessionDate: "Collection IX",
  },
  {
    id: "sg-9-video1",
    title: "Social Glam Look 15 - Video 1",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785270063/Video_Feb_14_2026_2_11_21_PM_tbu03f.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-9",
    sessionName: "Social Glam Series IX",
    sessionDate: "Collection IX",
    isVideo: true,
  },
  {
    id: "sg-9-video2",
    title: "Social Glam Look 15 - Video 2",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785270063/Video_Feb_14_2026_11_20_57_AM_n6zcfx.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-9",
    sessionName: "Social Glam Series IX",
    sessionDate: "Collection IX",
    isVideo: true,
  },

  // Session 10: Jun 06, 2026
  {
    id: "sg-10-photo1",
    title: "Social Glam Look 17",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785269275/Photo_Jun_06_2026_4_17_37_PM_j4nbha.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-10",
    sessionName: "Social Glam Series X",
    sessionDate: "Collection X",
    isSessionCover: true,
  },
  {
    id: "sg-10-video1",
    title: "Social Glam Look 17 - Video",
    label: "Social Glam",
    note: "Video capture of social glam look.",
    alt: "Social Glam makeup video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1785270063/Video_Jun_06_2026_4_17_14_PM_rr3pli.mp4",
    width: 1080,
    height: 1920,
    sessionId: "sg-series-10",
    sessionName: "Social Glam Series X",
    sessionDate: "Collection X",
    isVideo: true,
  },

  // Session 11: Jul 20, 2026
  {
    id: "sg-11-photo1",
    title: "Social Glam Look 18",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567817/Photo_Jul_20_2026_9_07_30_PM_22_kqibtl.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-11",
    sessionName: "Social Glam Series XI",
    sessionDate: "Collection XI",
    isSessionCover: true,
  },
  {
    id: "sg-11-photo2",
    title: "Social Glam Look 19",
    label: "Social Glam",
    note: "High-finish glam look with polished glow.",
    alt: "Social Glam makeup look",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567816/Photo_Jul_20_2026_9_07_30_PM_21_wbaxl1.jpg",
    width: 1400,
    height: 1750,
    sessionId: "sg-series-11",
    sessionName: "Social Glam Series XI",
    sessionDate: "Collection XI",
  },
];

export const photoshootAssets: PortfolioAsset[] = [
  // Main Hero Cover
  {
    id: "ps-hero-main",
    title: "Photoshoot Main Cover",
    label: "Photoshoot",
    note: "Polished beauty direction and editorial precision in front of the camera.",
    alt: "Photoshoot hero portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567804/Photo_Jul_20_2026_9_07_30_PM_2_ihb7zt.jpg",
    width: 1400,
    height: 1750,
    isHeroOnly: true,
  },

  // Session 1
  {
    id: "ps-1-photo1",
    title: "Photoshoot Look 01",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567821/Photo_Jul_20_2026_9_07_30_PM_27_ws4alk.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-1",
    sessionName: "Photoshoot Series I",
    sessionDate: "Collection I",
    isSessionCover: true,
  },
  {
    id: "ps-1-photo2",
    title: "Photoshoot Look 02",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567820/Photo_Jul_20_2026_9_07_30_PM_26_dkb0ta.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-1",
    sessionName: "Photoshoot Series I",
    sessionDate: "Collection I",
  },
  {
    id: "ps-1-photo3",
    title: "Photoshoot Look 03",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567820/Photo_Jul_20_2026_9_07_30_PM_25_1_gg4j3i.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-1",
    sessionName: "Photoshoot Series I",
    sessionDate: "Collection I",
  },
  {
    id: "ps-1-photo4",
    title: "Photoshoot Look 04",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567819/Photo_Jul_20_2026_9_07_30_PM_25_gnlgth.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-1",
    sessionName: "Photoshoot Series I",
    sessionDate: "Collection I",
  },

  // Session 3
  {
    id: "ps-3-photo1",
    title: "Photoshoot Look 07",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567816/Photo_Jul_20_2026_9_07_30_PM_20_j5nx15.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-3",
    sessionName: "Photoshoot Series III",
    sessionDate: "Collection III",
    isSessionCover: true,
  },
  {
    id: "ps-3-photo2",
    title: "Photoshoot Look 08",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567816/Photo_Jul_20_2026_9_07_30_PM_19_icurob.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-3",
    sessionName: "Photoshoot Series III",
    sessionDate: "Collection III",
  },
  {
    id: "ps-3-photo3",
    title: "Photoshoot Look 09",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567815/Photo_Jul_20_2026_9_07_30_PM_17_co6bky.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-3",
    sessionName: "Photoshoot Series III",
    sessionDate: "Collection III",
  },

  // Session 4
  {
    id: "ps-4-photo1",
    title: "Photoshoot Look 10",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567816/Photo_Jul_20_2026_9_07_30_PM_18_usk47b.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-4",
    sessionName: "Photoshoot Series IV",
    sessionDate: "Collection IV",
    isSessionCover: true,
  },
  {
    id: "ps-4-photo2",
    title: "Photoshoot Look 11",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567814/Photo_Jul_20_2026_9_07_30_PM_16_p0c04m.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-4",
    sessionName: "Photoshoot Series IV",
    sessionDate: "Collection IV",
  },

  // Session 2
  {
    id: "ps-2-photo1",
    title: "Photoshoot Look 05",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567819/Photo_Jul_20_2026_9_07_30_PM_24_tas2jw.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-2",
    sessionName: "Photoshoot Series II",
    sessionDate: "Collection II",
    isSessionCover: true,
  },
  {
    id: "ps-2-photo2",
    title: "Photoshoot Look 06",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567818/Photo_Jul_20_2026_9_07_30_PM_23_1_go4rfz.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-2",
    sessionName: "Photoshoot Series II",
    sessionDate: "Collection II",
  },

  // Session 5
  {
    id: "ps-5-photo1",
    title: "Photoshoot Look 14",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567813/Photo_Jul_20_2026_9_07_30_PM_14_yblw2z.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-5",
    sessionName: "Photoshoot Series V",
    sessionDate: "Collection V",
    isSessionCover: true,
  },
  {
    id: "ps-5-photo2",
    title: "Photoshoot Look 15",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567813/Photo_Jul_20_2026_9_07_30_PM_13_eenlar.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-5",
    sessionName: "Photoshoot Series V",
    sessionDate: "Collection V",
  },
  {
    id: "ps-5-photo3",
    title: "Photoshoot Look 16",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567809/Photo_Jul_20_2026_9_07_30_PM_9_b9lovd.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-5",
    sessionName: "Photoshoot Series V",
    sessionDate: "Collection V",
  },
  {
    id: "ps-5-photo4",
    title: "Photoshoot Look 17",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567811/Photo_Jul_20_2026_9_07_30_PM_10_1_p0fxsg.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-5",
    sessionName: "Photoshoot Series V",
    sessionDate: "Collection V",
  },

  // Session Kim (Photoshoot Series)
  {
    id: "ps-10b-photo1",
    title: "Photoshoot Look 25",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567804/Photo_Jul_20_2026_9_07_30_PM_2_ihb7zt.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-10b",
    sessionName: "Photoshoot Series X-B",
    sessionDate: "Collection X",
    isSessionCover: true,
  },
  {
    id: "ps-10b-photo2",
    title: "Photoshoot Look 25-B",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788718880/Rolando.Acunam_Kim010_zfynhg.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-10b",
    sessionName: "Photoshoot Series X-B",
    sessionDate: "Collection X",
  },
  {
    id: "ps-10b-photo3",
    title: "Photoshoot Look 25-C",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788718879/Rolando.Acunam_Kim007_v6okat.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-10b",
    sessionName: "Photoshoot Series X-B",
    sessionDate: "Collection X",
  },

  // Session 9
  {
    id: "ps-9-photo1",
    title: "Photoshoot Look 21",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567807/Photo_Jun_14_2026_12_15_08_PM_p9lu4c.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-9",
    sessionName: "Photoshoot Series IX",
    sessionDate: "Collection IX",
    isSessionCover: true,
  },
  {
    id: "ps-9-video1",
    title: "Photoshoot Look 21 - Video",
    label: "Photoshoot",
    note: "Video capture of photoshoot look.",
    alt: "Photoshoot beauty video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_1,f_mp4,q_auto/v1785567806/Video_May_20_2026_1_11_25_PM_jndq0l.mp4",
    width: 1080,
    height: 1920,
    sessionId: "ps-series-9",
    sessionName: "Photoshoot Series IX",
    sessionDate: "Collection IX",
    isVideo: true,
  },

  // Session 10
  {
    id: "ps-10-photo1",
    title: "Photoshoot Look 22",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567806/Photo_Jul_20_2026_9_07_30_PM_5_grlgsy.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-10",
    sessionName: "Photoshoot Series X",
    sessionDate: "Collection X",
    isSessionCover: true,
  },
  {
    id: "ps-10-photo2",
    title: "Photoshoot Look 23",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567805/Photo_Jul_20_2026_9_07_30_PM_3_tvgbru.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-10",
    sessionName: "Photoshoot Series X",
    sessionDate: "Collection X",
  },
  {
    id: "ps-10-photo3",
    title: "Photoshoot Look 24",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1785567805/Photo_Jul_20_2026_9_07_30_PM_4_af0jie.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-10",
    sessionName: "Photoshoot Series X",
    sessionDate: "Collection X",
  },

  // Session 11: Photoshoot Series XI
  {
    id: "ps-11-photo1",
    title: "Photoshoot Look 26",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786313015/Sophie04150_vn6i56.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-11",
    sessionName: "Photoshoot Series XI",
    sessionDate: "Collection XI",
    isSessionCover: true,
  },
  {
    id: "ps-11-photo2",
    title: "Photoshoot Look 27",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786313015/Sophie04223_eu0cxw.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-11",
    sessionName: "Photoshoot Series XI",
    sessionDate: "Collection XI",
  },
  {
    id: "ps-11-photo3",
    title: "Photoshoot Look 28",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786313014/Sophie04290_a7nwnc.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-11",
    sessionName: "Photoshoot Series XI",
    sessionDate: "Collection XI",
  },

  // Session 12: Photoshoot Series XII
  {
    id: "ps-12-photo1",
    title: "Photoshoot Look 29",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786313013/Mira-7362_kzlhym.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-12",
    sessionName: "Photoshoot Series XII",
    sessionDate: "Collection XII",
    isSessionCover: true,
  },
  {
    id: "ps-12-photo2",
    title: "Photoshoot Look 30",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786313011/Mira-7359_qwvmir.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-12",
    sessionName: "Photoshoot Series XII",
    sessionDate: "Collection XII",
  },
  {
    id: "ps-12-photo3",
    title: "Photoshoot Look 31",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1786313010/Mira-7087_ac61yd.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-12",
    sessionName: "Photoshoot Series XII",
    sessionDate: "Collection XII",
  },
  {
    id: "ps-12-photo4",
    title: "Photoshoot Look 31-B",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788719571/Mira_BTS-7377_u98v4c.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-12",
    sessionName: "Photoshoot Series XII",
    sessionDate: "Collection XII",
  },

  // Session 13: Photoshoot Series XIII
  {
    id: "ps-13-photo1",
    title: "Photoshoot Look 32",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788719395/Mira-6301_g6rxrd.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-13",
    sessionName: "Photoshoot Series XIII",
    sessionDate: "Collection XIII",
    isSessionCover: true,
  },
  {
    id: "ps-13-photo2",
    title: "Photoshoot Look 33",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788719396/Mira-6574_vcwdmz.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-13",
    sessionName: "Photoshoot Series XIII",
    sessionDate: "Collection XIII",
  },
  {
    id: "ps-13-photo3",
    title: "Photoshoot Look 34",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788719394/Mira-6295_xvzgvp.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-13",
    sessionName: "Photoshoot Series XIII",
    sessionDate: "Collection XIII",
  },
  {
    id: "ps-13-photo4",
    title: "Photoshoot Look 35",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788719396/Mira-6569_l5xfid.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-13",
    sessionName: "Photoshoot Series XIII",
    sessionDate: "Collection XIII",
  },

  // Session 14: Photoshoot Series XIV
  {
    id: "ps-14-photo1",
    title: "Photoshoot Look 36",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788720300/Rolando.Acunam_RWarehouse037_hohlxv.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-14",
    sessionName: "Photoshoot Series XIV",
    sessionDate: "Collection XIV",
    isSessionCover: true,
  },
  {
    id: "ps-14-photo2",
    title: "Photoshoot Look 37",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788720302/Rolando.Acunam_RWarehouse043_kzsctv.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-14",
    sessionName: "Photoshoot Series XIV",
    sessionDate: "Collection XIV",
  },

  // Session 15: Photoshoot Series XV
  {
    id: "ps-15-photo1",
    title: "Photoshoot Look 38",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788720304/Rolando.Acunam_RWarehouse045_azjoba.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-15",
    sessionName: "Photoshoot Series XV",
    sessionDate: "Collection XV",
    isSessionCover: true,
    startsNewRow: true,
  },
  {
    id: "ps-15-photo2",
    title: "Photoshoot Look 39",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788720303/Rolando.Acunam_RWarehouse047_une3ib.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-15",
    sessionName: "Photoshoot Series XV",
    sessionDate: "Collection XV",
  },
  {
    id: "ps-15-photo3",
    title: "Photoshoot Look 40",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788720305/Rolando.Acunam_RWarehouse049_vxlo91.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-15",
    sessionName: "Photoshoot Series XV",
    sessionDate: "Collection XV",
  },
  {
    id: "ps-15-photo4",
    title: "Photoshoot Look 41",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788720306/Rolando.Acunam_RWarehouse050_c9r4s7.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-15",
    sessionName: "Photoshoot Series XV",
    sessionDate: "Collection XV",
  },

  // Session 16: Photoshoot Series XVI
  {
    id: "ps-16-photo1",
    title: "Photoshoot Look 42",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788720851/Mo5415_eczrif.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-16",
    sessionName: "Photoshoot Series XVI",
    sessionDate: "Collection XVI",
    isSessionCover: true,
  },
  {
    id: "ps-16-photo2",
    title: "Photoshoot Look 43",
    label: "Photoshoot",
    note: "Polished beauty direction and skin focus.",
    alt: "Photoshoot beauty portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788720852/Mo5438_wypdpp.jpg",
    width: 1400,
    height: 1750,
    sessionId: "ps-series-16",
    sessionName: "Photoshoot Series XVI",
    sessionDate: "Collection XVI",
  },
];

export const hairAssets: PortfolioAsset[] = [
  // Session 1: Hair Series I
  {
    id: "hair-1-photo1",
    title: "Hair Style 01",
    label: "Hair",
    note: "",
    alt: "Hair styling portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788527431/IMG_6547_xfkhtf.jpg",
    width: 1400,
    height: 1750,
    sessionId: "hair-series-1",
    sessionName: "Hair Series I",
    sessionDate: "Collection I",
    isSessionCover: true,
  },
  {
    id: "hair-1-photo2",
    title: "Hair Style 02",
    label: "Hair",
    note: "",
    alt: "Hair styling portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788527430/IMG_6519_t5rq6x.heic",
    width: 1400,
    height: 1750,
    sessionId: "hair-series-1",
    sessionName: "Hair Series I",
    sessionDate: "Collection I",
  },
  {
    id: "hair-1-photo3",
    title: "Hair Style 03",
    label: "Hair",
    note: "",
    alt: "Hair styling portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788527430/IMG_6520_dtu074.heic",
    width: 1400,
    height: 1750,
    sessionId: "hair-series-1",
    sessionName: "Hair Series I",
    sessionDate: "Collection I",
  },

  // Session 2: Hair Series II
  {
    id: "hair-2-photo1",
    title: "Hair Style 04",
    label: "Hair",
    note: "",
    alt: "Hair styling portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788527434/IMG_7931_zcgfbr.jpg",
    width: 1400,
    height: 1750,
    sessionId: "hair-series-2",
    sessionName: "Hair Series II",
    sessionDate: "Collection II",
    isSessionCover: true,
  },
  {
    id: "hair-2-photo2",
    title: "Hair Style 05",
    label: "Hair",
    note: "",
    alt: "Hair styling portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788527434/IMG_7932_wgki8o.jpg",
    width: 1400,
    height: 1750,
    sessionId: "hair-series-2",
    sessionName: "Hair Series II",
    sessionDate: "Collection II",
  },

  // Session 3: Hair Series III
  {
    id: "hair-3-photo1",
    title: "Hair Style 06",
    label: "Hair",
    note: "",
    alt: "Hair styling portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788527433/IMG_7930_1_brkjwh.jpg",
    width: 1400,
    height: 1750,
    sessionId: "hair-series-3",
    sessionName: "Hair Series III",
    sessionDate: "Collection III",
    isSessionCover: true,
  },
  {
    id: "hair-3-photo2",
    title: "Hair Style 07",
    label: "Hair",
    note: "",
    alt: "Hair styling portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788527432/IMG_7929_1_ow98fw.jpg",
    width: 1400,
    height: 1750,
    sessionId: "hair-series-3",
    sessionName: "Hair Series III",
    sessionDate: "Collection III",
  },

  // Session 4: Hair Series IV
  {
    id: "hair-4-photo1",
    title: "Hair Style 08",
    label: "Hair",
    note: "",
    alt: "Hair styling portrait",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/image/upload/v1788527429/Photo_Aug_29_2026_4_20_09_PM_taxmpa.jpg",
    width: 1400,
    height: 1750,
    sessionId: "hair-series-4",
    sessionName: "Hair Series IV",
    sessionDate: "Collection IV",
    isSessionCover: true,
  },
  {
    id: "hair-4-video",
    title: "Hair Style 08 - Video",
    label: "Hair",
    note: "Video capture of hair styling.",
    alt: "Hair styling video",
    imageUrl: "https://res.cloudinary.com/dqcpmau9i/video/upload/ac_none,so_0,eo_4,f_mp4,q_auto/v1788527430/Video_Sep_03_2026_6_23_13_PM_r7ceyz.mp4",
    width: 1080,
    height: 1920,
    sessionId: "hair-series-4",
    sessionName: "Hair Series IV",
    sessionDate: "Collection IV",
    isVideo: true,
  },
];

export function getPortfolioModule(slug: string) {
  return portfolioModules.find((module) => module.slug === slug);
}

export async function getPortfolioAssets(slug?: string) {
  if (slug === "key-projects") {
    return { assets: keyProjectsAssets, source: "key-projects" as const };
  }
  if (slug === "editorials") {
    return { assets: editorialAssets, source: "editorials" as const };
  }
  if (slug === "timeless-beauty") {
    return { assets: timelessAssets, source: "timeless-beauty" as const };
  }
  if (slug === "social-glam") {
    return { assets: socialGlamAssets, source: "social-glam" as const };
  }
  if (slug === "photoshoot") {
    return { assets: photoshootAssets, source: "photoshoot" as const };
  }
  if (slug === "hair") {
    return { assets: hairAssets, source: "hair" as const };
  }

  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
  const apiKey = process.env.CLOUDINARY_API_KEY;
  const apiSecret = process.env.CLOUDINARY_API_SECRET;

  if (!cloudName || !apiKey || !apiSecret) {
    return { assets: curatedAssets, source: "fallback" as const };
  }

  const endpoint = new URL(`https://api.cloudinary.com/v1_1/${cloudName}/resources/image/upload`);
  endpoint.searchParams.set("max_results", "100");

  try {
    const response = await fetch(endpoint, {
      headers: {
        Authorization: `Basic ${Buffer.from(`${apiKey}:${apiSecret}`).toString("base64")}`,
      },
      next: { revalidate: 3600 },
    });

    if (!response.ok) {
      return { assets: curatedAssets, source: "fallback" as const };
    }

    const payload = (await response.json()) as { resources?: CloudinaryResource[] };
    const resources = payload.resources?.filter((resource) => resource.secure_url) ?? [];
    const assetMap = new Map(resources.map((resource) => [resource.secure_url.replace(/\/upload\/.+?\/v/, "/upload/q_auto/f_auto/v"), resource]));

    const assets = curatedAssets.map((asset) => {
      const matchingResource = assetMap.get(asset.imageUrl);

      if (!matchingResource) {
        return asset;
      }

      return {
        ...asset,
        width: matchingResource.width ?? asset.width,
        height: matchingResource.height ?? asset.height,
      };
    });

    return { assets, source: "api" as const };
  } catch {
    return { assets: curatedAssets, source: "fallback" as const };
  }
}